modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="conquestchat"
version="1.0.0"
displayName="ConquestChat"
authors="CONQUEST PROTOCOL"
description='''
Advanced chat system with multiple channels and tabs.
Global, Trade, Combat, and Private messaging support.
'''

[[dependencies.conquestchat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.conquestchat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
